title = 'LearnixOS'
baseURL = 'https://learnixOS.github.io/'
languageCode = 'en-us'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[params]
site_logo = "images/learnix-title-logo.png"
favicon = "images/favicon/favicon.ico"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/LearnixOS/LearnixOS"
